{% set name = "pyxDamerauLevenshtein" %}
{% set version = "1.7.0" %}
{% set sha256 = "a85ec151f59455462ae62244d3fc16c16b33ddcf662be3e75bb8f89a862a942b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gfairchild/pyxDamerauLevenshtein/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - numpy
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pyxdameraulevenshtein

about:
  home: https://github.com/gfairchild/pyxDamerauLevenshtein
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: High performance Damerau-Levenshtein (DL) edit distance algorithm for Python.
  # The remaining entries in this section are optional, but recommended
  description: |
    pyxDamerauLevenshtein implements the Damerau-Levenshtein (DL) edit distance
    algorithm for Python in Cython for high performance.
  doc_url: https://github.com/gfairchild/pyxDamerauLevenshtein
  dev_url: https://github.com/gfairchild/pyxDamerauLevenshtein
