{% set name = "pyxDamerauLevenshtein" %}
{% set version = "1.6.1" %}
{% set sha256 = "26f843b0af9e04e538c7a2eda51ce9bcbd3f5723a1e5c6ff842fca11f5a08b27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gfairchild/pyxDamerauLevenshtein/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - numpy
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pyxdameraulevenshtein

about:
  home: https://github.com/gfairchild/pyxDamerauLevenshtein
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: High performance Damerau-Levenshtein (DL) edit distance algorithm for Python.
  # The remaining entries in this section are optional, but recommended
  description: |
    pyxDamerauLevenshtein implements the Damerau-Levenshtein (DL) edit distance
    algorithm for Python in Cython for high performance.
  doc_url: https://github.com/gfairchild/pyxDamerauLevenshtein
  dev_url: https://github.com/gfairchild/pyxDamerauLevenshtein
